.TH "headers Directory Reference" 3 "Wed Apr 22 2020" "QuantumGates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmatrixOperation\&.h\fP"
.br
.ti -1c
.RI "file \fBquantumComputer\&.h\fP"
.br
.ti -1c
.RI "file \fBquantumGate\&.h\fP"
.br
.ti -1c
.RI "file \fBquantumGateOperation\&.h\fP"
.br
.ti -1c
.RI "file \fBqubitOperation\&.h\fP"
.br
.in -1c
