.TH "quantumComputer.h" 3 "Wed Apr 22 2020" "QuantumGates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
quantumComputer.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBquantum::QuantumComputer\fP"
.br
.RI "\fBQuantumComputer\fP structure\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBquantum\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QuantumGates from the source code\&.
