.TH "quantum" 3 "Tue Jun 2 2020" "QuantumGates" \" -*- nroff -*-
.ad l
.nh
.SH NAME
quantum
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBQuantumComputer\fP"
.br
.RI "\fBQuantumComputer\fP structure\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QuantumGates from the source code\&.
